// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: api-gateway/service.proto

package api_gateway

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_gateway_service_proto protoreflect.FileDescriptor

const file_api_gateway_service_proto_rawDesc = "" +
	"\n" +
	"\x19api-gateway/service.proto\x12\fgo_messenger\x1a\x1aapi-gateway/messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto2\xe0\x06\n" +
	"\x11ApiGatewayService\x12j\n" +
	"\bRegister\x12\x1d.go_messenger.RegisterRequest\x1a\".go_messenger.UserRegisterResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/register\x12^\n" +
	"\x05Login\x12\x1a.go_messenger.LoginRequest\x1a\x1f.go_messenger.UserLoginResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/login\x12i\n" +
	"\fRefreshToken\x12\x16.google.protobuf.Empty\x1a\".go_messenger.RefreshTokenResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\"\x15/api/v1/refresh_token\x12V\n" +
	"\x06Logout\x12\x16.google.protobuf.Empty\x1a\x1c.go_messenger.LogoutResponse\"\x16\x82\xd3\xe4\x93\x02\x10\"\x0e/api/v1/logout\x12^\n" +
	"\aGetUser\x12\x1c.go_messenger.GetUserRequest\x1a\x19.go_messenger.UserProfile\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/users/{id}\x12g\n" +
	"\n" +
	"GetProfile\x12\x1f.go_messenger.GetProfileRequest\x1a\x19.go_messenger.UserProfile\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/users/profile\x12z\n" +
	"\rUpdateProfile\x12\".go_messenger.UpdateProfileRequest\x1a#.go_messenger.UpdateProfileResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*2\x15/api/v1/users/profile\x12w\n" +
	"\rDeleteProfile\x12\".go_messenger.DeleteProfileRequest\x1a#.go_messenger.DeleteProfileResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/users/profileB\x11Z\x0fpkg/api-gatewayb\x06proto3"

var file_api_gateway_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: go_messenger.RegisterRequest
	(*LoginRequest)(nil),          // 1: go_messenger.LoginRequest
	(*emptypb.Empty)(nil),         // 2: google.protobuf.Empty
	(*GetUserRequest)(nil),        // 3: go_messenger.GetUserRequest
	(*GetProfileRequest)(nil),     // 4: go_messenger.GetProfileRequest
	(*UpdateProfileRequest)(nil),  // 5: go_messenger.UpdateProfileRequest
	(*DeleteProfileRequest)(nil),  // 6: go_messenger.DeleteProfileRequest
	(*UserRegisterResponse)(nil),  // 7: go_messenger.UserRegisterResponse
	(*UserLoginResponse)(nil),     // 8: go_messenger.UserLoginResponse
	(*RefreshTokenResponse)(nil),  // 9: go_messenger.RefreshTokenResponse
	(*LogoutResponse)(nil),        // 10: go_messenger.LogoutResponse
	(*UserProfile)(nil),           // 11: go_messenger.UserProfile
	(*UpdateProfileResponse)(nil), // 12: go_messenger.UpdateProfileResponse
	(*DeleteProfileResponse)(nil), // 13: go_messenger.DeleteProfileResponse
}
var file_api_gateway_service_proto_depIdxs = []int32{
	0,  // 0: go_messenger.ApiGatewayService.Register:input_type -> go_messenger.RegisterRequest
	1,  // 1: go_messenger.ApiGatewayService.Login:input_type -> go_messenger.LoginRequest
	2,  // 2: go_messenger.ApiGatewayService.RefreshToken:input_type -> google.protobuf.Empty
	2,  // 3: go_messenger.ApiGatewayService.Logout:input_type -> google.protobuf.Empty
	3,  // 4: go_messenger.ApiGatewayService.GetUser:input_type -> go_messenger.GetUserRequest
	4,  // 5: go_messenger.ApiGatewayService.GetProfile:input_type -> go_messenger.GetProfileRequest
	5,  // 6: go_messenger.ApiGatewayService.UpdateProfile:input_type -> go_messenger.UpdateProfileRequest
	6,  // 7: go_messenger.ApiGatewayService.DeleteProfile:input_type -> go_messenger.DeleteProfileRequest
	7,  // 8: go_messenger.ApiGatewayService.Register:output_type -> go_messenger.UserRegisterResponse
	8,  // 9: go_messenger.ApiGatewayService.Login:output_type -> go_messenger.UserLoginResponse
	9,  // 10: go_messenger.ApiGatewayService.RefreshToken:output_type -> go_messenger.RefreshTokenResponse
	10, // 11: go_messenger.ApiGatewayService.Logout:output_type -> go_messenger.LogoutResponse
	11, // 12: go_messenger.ApiGatewayService.GetUser:output_type -> go_messenger.UserProfile
	11, // 13: go_messenger.ApiGatewayService.GetProfile:output_type -> go_messenger.UserProfile
	12, // 14: go_messenger.ApiGatewayService.UpdateProfile:output_type -> go_messenger.UpdateProfileResponse
	13, // 15: go_messenger.ApiGatewayService.DeleteProfile:output_type -> go_messenger.DeleteProfileResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_gateway_service_proto_init() }
func file_api_gateway_service_proto_init() {
	if File_api_gateway_service_proto != nil {
		return
	}
	file_api_gateway_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_service_proto_rawDesc), len(file_api_gateway_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_service_proto_goTypes,
		DependencyIndexes: file_api_gateway_service_proto_depIdxs,
	}.Build()
	File_api_gateway_service_proto = out.File
	file_api_gateway_service_proto_goTypes = nil
	file_api_gateway_service_proto_depIdxs = nil
}
